language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: QjQL8PUAuGW3us2hbhGDnEeLYJ9g/xpbsBJGamsIYfEtAD5aOWbAEmVEXxwPvbP5aPf2JlHrjWMstHEHAMiX4RNmvBNMu8qCwCxLdvk8093f4O5nQ1+jdRCIr8n0uvw1ARDP2vZcxn8GcdIWcLtER7A/DXZ64EJipu1IvsfBle4=
